fix

diff --git a/.devops/deploy-pipelines.yml b/.devops/deploy-pipelines.yml
--- a/.devops/deploy-pipelines.yml
+++ b/.devops/deploy-pipelines.yml
@@ -77,18 +77,20 @@ stages:
             inputs:
               containerRegistry: 'io-p-messages-acr-docker-registry-prod'
               command: 'login'
-      - script: |
-          # docker will return 0 on success or 1 on failure.
-          docker manifest inspect iopcommonacr/io-functions-service-messages:latest > /dev/null ;
-          if [ $? -eq 0 ]; then
-            echo "image already exist"
-          else
-            echo "new image"
-            docker build -t iopcommonacr/io-functions-service-messages:$(Build.BuildId) .
-            docker build -t iopcommonacr/io-functions-service-messages:latest .
-            docker push iopcommonacr/io-functions-service-messages:$(Build.BuildId)
-            docker push iopcommonacr/io-functions-service-messages:latest
-          fi
+          - task: Bash@3
+            inputs:
+              targetType: 'inline'
+              script: |
+                # docker will return 0 on success or 1 on failure.
+                docker manifest inspect iopcommonacr/io-functions-service-messages:latest > /dev/null ;
+                if [ $? -eq 0 ]; then
+                  echo "image already exist"
+                else
+                  echo "new image"
+                  docker build -t iopcommonacr/io-functions-service-messages:$(Build.BuildId) .
+                  docker build -t iopcommonacr/io-functions-service-messages:latest .
+                  docker push iopcommonacr/io-functions-service-messages:$(Build.BuildId)
+                  docker push iopcommonacr/io-functions-service-messages:latest
       # - job: 'build'
       #   steps:
       #     - task: Docker@2
