new dockerfile

diff --git a/.devops/deploy-pipelines.yml b/.devops/deploy-pipelines.yml
--- a/.devops/deploy-pipelines.yml
+++ b/.devops/deploy-pipelines.yml
@@ -12,6 +12,13 @@ parameters:
       - minor
       - patch
     default: minor
+  - name: 'FORCE_REPLACE_DOCKER_IMAGE'
+    displayName: 'Force the existing docker image to be replaced'
+    type: boolean
+    default: False
+    values:
+      - False
+      - True
 
 # Only manual activations are intended
 trigger: none
@@ -82,12 +89,17 @@ stages:
             inputs:
               targetType: 'inline'
               script: |
-                # docker will return 0 on success or 1 on failure.
-                docker manifest inspect iopcommonacr.azurecr.io/io-functions-service-messages:latest > /dev/null
-                if [ $? -eq 0 ]; then
-                  echo "the image exists in the registry, skip build and push"
+                if [ ${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }} == "True" ]; then
+                  echo "Parameter FORCE_REPLACE_DOCKER_IMAGE is set to true, we'll replace existing docker image"
                 else
-                  echo "the image does not exist in the registry, start build and push"
+                  # docker will return 0 on success or 1 on failure.
+                  docker manifest inspect iopcommonacr.azurecr.io/io-functions-service-messages:latest > /dev/null
+                fi
+
+                if [ $? -eq 0 ]; then
+                  echo "docker image already exists in the registry, skip build and push"
+                else
+                  echo "docker image does not exist in the registry or the parameter FORCE_REPLACE_DOCKER_IMAGE is set to true, start build and push"
                   docker build -t iopcommonacr.azurecr.io/io-functions-service-messages:$(Build.BuildId) .
                   docker build -t iopcommonacr.azurecr.io/io-functions-service-messages:latest .
                   docker push iopcommonacr.azurecr.io/io-functions-service-messages:$(Build.BuildId)
